# snip shell completion — generated by snip
_snip_completions() {
    local cur prev cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd="${COMP_WORDS[1]}"

    # Complete subcommands
    if [ "$COMP_CWORD" -eq 1 ]; then
        # Add dynamic snippet names from .snips
        local snippets
        snippets=$(snip _complete snippets 2>/dev/null)
        local subcommands="init add rm edit list run import doctor completions hook suggest explain stale setup"
        COMPREPLY=( $(compgen -W "$subcommands $snippets" -- "$cur") )
        return 0
    fi

    # Complete snippet names for 'run' subcommand
    case "$cmd" in
        run|explain)
            local snippets
            snippets=$(snip _complete snippets 2>/dev/null)
            COMPREPLY=( $(compgen -W "$snippets" -- "$cur") )
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish nushell elvish powershell" -- "$cur") )
            ;;
        rm)
            local snippets
            snippets=$(snip _complete snippets 2>/dev/null)
            COMPREPLY=( $(compgen -W "$snippets" -- "$cur") )
            ;;
        add)
            # No completion for add arguments
            ;;
        doctor)
            COMPREPLY=( $(compgen -W "--fix" -- "$cur") )
            ;;
        list)
            COMPREPLY=( $(compgen -W "--json --format --section" -- "$cur") )
            ;;
        stale)
            COMPREPLY=( $(compgen -W "--fix --json" -- "$cur") )
            ;;
    esac
}

complete -F _snip_completions snip